Vagrant.configure("2") do |config|
  

  config.vm.define "archreactor.org" do |node|
    node.vm.hostname = "archreactor-org"
    node.vm.box = "ubuntu/xenial64"
    node.vm.network :private_network, :ip => '10.20.1.2'
    node.vm.provision :hosts, :sync_hosts => true
    node.vm.provision :ansible do |ansible|
      ansible.playbook = "test_key_deploy_playbook.yml"
    end
  end

  config.vm.define "archreactor.net" do |node|
    node.vm.hostname = "archreactor-net"
    node.vm.box = "ubuntu/bionic64"
    node.vm.network :private_network, :ip => '10.20.1.3'
    node.vm.provision :hosts, :sync_hosts => true
    node.vm.provision :ansible do |ansible|
      ansible.playbook = "test_key_deploy_playbook.yml"
    end
  end

  config.vm.define "test-desktop" do |node|
    node.vm.box = "chenhan/lubuntu-desktop-18.04"
    node.vm.box_version = "20180704.0.0"
    node.vm.network :private_network, :ip => '10.20.1.4'
    node.vm.provision :hosts, :sync_hosts => true
    node.vm.synced_folder "../", "/vagrant"
    node.vm.provider "virtualbox" do |v|
      v.gui = true
    end
    node.vm.provision :ansible do |ansible|
      ansible.playbook = "test_desktop_setup_playbook.yml"
    end
    node.vm.provision :ansible do |ansible|
      ansible.playbook = "test_key_deploy_playbook.yml"
    end
  end
end
