---

- hosts: docker_host

  vars:
    pip_install_packages:
      - name: docker

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

  roles:
    - { role: geerlingguy.docker, become: true }
    - { role: geerlingguy.pip, become: true }
