---

- hosts: docker_host

  vars:
    pip_install_packages:
      - name: docker
    pip_executable: pip2

  roles:
    - { role: geerlingguy.docker, become: true }
    - { role: geerlingguy.pip, become: true }
