---

- hosts: jenkins_server

  tasks:

  - name: Create Volume for Jenkins
    docker_volume:
      name: jenkins_home

  # https://github.com/4OH4/jenkins-docker
  - name: Download and Deploy Jenkins with Docker built in
    docker_container:
      name: jenkins
      image: 4oh4/jenkins-docker
      ports:
        - "8088:8080"
      restart_policy: always
      volumes:
        - jenkins_home:/var/jenkins_home
        - /etc/timezone:/etc/timezone:ro
        - /var/run/docker.sock:/var/run/docker.sock:rw
        - /srv/rsync/backups:/srv
      user: "1000:998"
      restart_policy: "always"
