---

- hosts: keycloak_server

  vars:

    KEYCLOAK_PORT: 9909
    KEYCLOAK_SSL_PORT: 443
    KEYCLOAK_HOST: "users.archreactor.net"

    nginx_redirects:
      - from: "{{ KEYCLOAK_HOST }}"
        to: "127.0.0.1:{{ KEYCLOAK_PORT }}"

  roles:
    - role: nginx

  tasks:

    - name: Generate redirect config
      template:
        src: nginx_redirect.j2
        dest: /etc/nginx/sites-enabled/users.archreactor.net.conf
        owner: www-data
        group: www-data
      notify: restart nginx
      become: yes

    - name: Install Keycloak
      docker_container:
        image: jboss/keycloak
        name: keycloak
        env:
          KEYCLOAK_USER: "admin"
          KEYCLOAK_PASSWORD: "admin"
          DB_VENDOR: "h2"
          PROXY_ADDRESS_FORWARDING: "true"
        volumes:
          - "/etc/letsencrypt/live/users.archreactor.net/fullchain.pem:/etc/x509/https/tls.crt"
          - "/etc/letsencrypt/live/users.archreactor.net/privkey.pem:/etc/x509/https/tls.key"
        ports:
          - "{{ KEYCLOAK_PORT }}:8080"
          - "{{ KEYCLOAK_SSL_PORT }}:8443"
        restart_policy: "unless-stopped"
        restart: yes
    
    - name: Wait for keycloak to start
      wait_for:
        host: "{{ KEYCLOAK_HOST }}"
        port: "80"
        timeout: 8