---
- hosts: keycloak_server

  vars:
    KEYCLOAK_PORT: 9909
    KEYCLOAK_SSL_PORT: 8443
    KEYCLOAK_HOST: 'users.archreactor.net'

  tasks:
    - name: Create Volume for Keycloak data
      docker_volume:
        name: keycloak_data

    - name: Install Keycloak
      docker_container:
        image: jboss/keycloak:10.0.2
        name: keycloak
        env:
          KEYCLOAK_USER: 'admin'
          KEYCLOAK_PASSWORD: 'admin'
          DB_VENDOR: 'h2'
          PROXY_ADDRESS_FORWARDING: 'true'
        volumes:
          - 'keycloak_data:/opt/jboss/keycloak/standalone/data'
          - '/etc/letsencrypt/live/users.archreactor.net/fullchain.pem:/etc/x509/https/tls.crt'
          - '/etc/letsencrypt/live/users.archreactor.net/privkey.pem:/etc/x509/https/tls.key'
        ports:
          - '{{ KEYCLOAK_PORT }}:8080'
          - '{{ KEYCLOAK_SSL_PORT }}:8443'
        restart_policy: 'unless-stopped'
        restart: yes

    - name: Wait for keycloak to start
      wait_for:
        host: '{{ KEYCLOAK_HOST }}'
        port: '80'
        timeout: 8
