---

- hosts: ldap_server

  vars:
    nginx_redirects:
      - from: "ldap.archreactor.net"
        to: "127.0.0.1:4432"

  roles:
    - role: nginx

  tasks:

    - name: Generate redirect config
      template:
        src: nginx_redirect.j2
        dest: /etc/nginx/sites-enabled/ldap.archreactor.net.conf
        owner: www-data
        group: www-data
      notify: restart nginx
      become: yes

    # https://github.com/osixia/docker-phpLDAPadmin      
    - name: Install phpldapadmin
      docker_container:
        image: osixia/phpldapadmin:0.9.0
        name: phpldapadmin-service
        hostname: phpldapadmin-service
        env:
          PHPLDAPADMIN_LDAP_HOSTS: "10.42.20.143"
          PHPLDAPADMIN_HTTPS: "false"
        ports:
          - "4432:80"
        restart_policy: "always"