---
- hosts: archreactor_api_server

  vars:
    NODE_RED_PORT: 1880
    VOLUME_NAME: 'node-red'

  tasks:
    - name: Created docker volume for Node red
      docker_volume:
        name: '{{ VOLUME_NAME }}'

    - name: Run Node Red server
      docker_container:
        name: 'node-red'
        image: 'nodered/node-red'
        ports:
          - '{{ NODE_RED_PORT }}:1880'
        volumes:
          - '{{ VOLUME_NAME }}:/data'
        etc_hosts:
          api.archreactor.net: '{{ ansible_default_ipv4.address }}'
          users.archreactor.net: '{{ ansible_default_ipv4.address }}'
          tools.archreactor.net: '{{ ansible_default_ipv4.address }}'
        restart_policy: 'always'
        restart: yes
