---

- hosts: sensu_backend

  vars_files:
    - "{{ VAULT_FOLDER }}/secrets.yml"

  vars:
    SENSU_URL: "http://archreactor.org:8080"
    SENSU_USER: "admin"
    SENSU_PASS: "P@ssw0rd!"

  tasks:
    - name: Ping test
      ping:

    - name: Create sensu network for docker
      docker_network:
        name: sensu

    - name: Create sensu volume for docker
      docker_volume:
        name: sensu-backend-data

    - name: Deploy sensu backend server via docker
      docker_container:
        image: sensu/sensu:5.17.1
        name: sensu-backend
        ports:
          - "8080:8080"
          - "8081:8081"
          - "3000:3000"
        env:
          SENSU_BACKEND_CLUSTER_ADMIN_USERNAME: "{{ SENSU_USER }}"
          SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD: "{{ SENSU_PASS }}"
        networks: 
          - name: "sensu"
        volumes:
          - "sensu-backend-data:/var/lib/sensu"
        command: "sensu-backend start --log-level debug"
        restart_policy: "unless-stopped"

    - name: Install Slack asset
      sensu.sensu_go.bonsai_asset:
        name: sensu/sensu-slack-handler
        version: 1.2.0
  
    - name: Setup filter to Only notify on state change
      sensu.sensu_go.filter:
        name: state_change_only
        action: allow
        expressions:
          - event.check.occurrences == 1
  
    - name: Install Slack handler
      sensu.sensu_go.pipe_handler:
        name: slack
        env_vars:
          SLACK_WEBHOOK_URL: "{{ SLACK_WEBHOOK_ENDPOINT }}"
        command: "sensu-slack-handler --channel '#alerts'"
        filters:
          - is_incident
          - state_change_only
          - not_silenced
        runtime_assets:
          - sensu/sensu-slack-handler
  
    - name: Install Disk check asset
      sensu.sensu_go.bonsai_asset:
        name: sensu-plugins/sensu-plugins-disk-checks
        version: 5.0.1
  
    - name: Install Ruby runtime asset
      sensu.sensu_go.bonsai_asset:
        name: sensu/sensu-ruby-runtime
        version: 0.0.10
  
    - name: Add disk check
      sensu.sensu_go.check:
        name: disk_check
        command: "check-disk-usage.rb -p '(\\/var|\\/run|\\/sys|\\/snap)'"
        subscriptions:
          - checks
        interval: 86400
        runtime_assets:
          - sensu/sensu-ruby-runtime
          - sensu-plugins/sensu-plugins-disk-checks
        handlers:
          - slack
        publish: yes
    
    - name: Install load check asset
      sensu.sensu_go.bonsai_asset:
        name: sensu-plugins/sensu-plugins-load-checks
        version: 5.1.0
  
    - name: Add load check
      sensu.sensu_go.check:
        name: load_check
        command: "check-load.rb"
        subscriptions:
          - checks
        interval: 1200
        runtime_assets:
          - sensu/sensu-ruby-runtime
          - sensu-plugins/sensu-plugins-load-checks
        handlers:
          - slack
        publish: yes
    
    - name: Install memory check asset
      sensu.sensu_go.bonsai_asset:
        name: sensu-plugins/sensu-plugins-memory-checks
        version: 4.1.1
  
    - name: Add memory check
      sensu.sensu_go.check:
        name: memory_check
        command: "check-memory-percent.rb"
        subscriptions:
          - checks
        interval: 1200
        runtime_assets:
          - sensu/sensu-ruby-runtime
          - sensu-plugins/sensu-plugins-memory-checks
        handlers:
          - slack
        publish: yes
      
    - name: Install https://monitoring-plugins.org assets
      sensu.sensu_go.bonsai_asset:
        name: sensu/monitoring-plugins
        version: 2.5.0

    - name: Add Wordpress check
      sensu.sensu_go.check:
        name: worpress
        command: "check_http -H archreactor.org -p 88"
        subscriptions:
          - checks
        interval: 120
        runtime_assets:
          - sensu/monitoring-plugins
        handlers:
          - slack
        publish: yes

    - name: Add check for Jenkins
      sensu.sensu_go.check:
        name: jenkins
        command: "check_http -H jenkins.archreactor.net"
        subscriptions:
          - checks
        interval: 120
        runtime_assets:
          - sensu/monitoring-plugins
        handlers:
          - slack
        publish: yes

    - name: Add check for snipe-it
      sensu.sensu_go.check:
        name: snipe-it
        command: "check_http -H tools.archreactor.net"
        subscriptions:
          - checks
        interval: 120
        runtime_assets:
          - sensu/monitoring-plugins
        handlers:
          - slack
        publish: yes

- hosts: sensu_agent
  
  vars:
    agent_config:
      backend-url: "ws://archreactor.org:8081"
      subscriptions: "{{ SENSU_CHECKS }}"
      
  roles:
    - role: sensu.sensu_go.agent
      become: yes