---
- hosts: sensu_backend

  vars_files:
    - '{{ VAULT_FOLDER }}/secrets.yml'

  tasks:
    - name: Create sensu network for docker
      docker_network:
        name: sensu

    - name: Create sensu volume for docker
      docker_volume:
        name: sensu-backend-data

    - name: Deploy sensu backend server via docker
      docker_container:
        image: sensu/sensu:5.17.1
        name: sensu-backend
        ports:
          - '8080:8080'
          - '8081:8081'
          - '3000:3000'
        env:
          SENSU_BACKEND_CLUSTER_ADMIN_USERNAME: '{{ SENSU_AUTH.user }}'
          SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD: '{{ SENSU_AUTH.password }}'
        networks:
          - name: 'sensu'
        volumes:
          - 'sensu-backend-data:/var/lib/sensu'
        log_driver: json-file
        log_options:
          max-size: 10m
          max-file: 3
        command: 'sensu-backend start'
        restart_policy: 'always'

    - name: Wait for sensu to start
      wait_for:
        port: '3000'
        timeout: 20

    - name: Install Slack asset
      sensu.sensu_go.bonsai_asset:
        auth: '{{ SENSU_AUTH }}'
        name: sensu/sensu-slack-handler
        version: 1.2.0

    - name: Setup filter to Only notify on state change
      sensu.sensu_go.filter:
        auth: '{{ SENSU_AUTH }}'
        name: state_change_and_hold
        action: allow
        expressions:
          - event.check.occurrences == 2

    - name: Install Slack handler
      sensu.sensu_go.pipe_handler:
        auth: '{{ SENSU_AUTH }}'
        name: slack
        env_vars:
          SLACK_WEBHOOK_URL: '{{ SLACK_WEBHOOK_ENDPOINT }}'
        command: "sensu-slack-handler --channel '#alerts'"
        filters:
          - is_incident
          - state_change_and_hold
          - not_silenced
        runtime_assets:
          - sensu/sensu-slack-handler

    - name: Install Disk check asset
      sensu.sensu_go.bonsai_asset:
        auth: '{{ SENSU_AUTH }}'
        name: sensu-plugins/sensu-plugins-disk-checks
        version: 5.0.1

    - name: Install Ruby runtime asset
      sensu.sensu_go.bonsai_asset:
        auth: '{{ SENSU_AUTH }}'
        name: sensu/sensu-ruby-runtime
        version: 0.0.10

    - name: Install load check asset
      sensu.sensu_go.bonsai_asset:
        auth: '{{ SENSU_AUTH }}'
        name: sensu-plugins/sensu-plugins-load-checks
        version: 5.1.0

    - name: Install memory check asset
      sensu.sensu_go.bonsai_asset:
        auth: '{{ SENSU_AUTH }}'
        name: sensu-plugins/sensu-plugins-memory-checks
        version: 4.1.1

    - name: Install https://monitoring-plugins.org assets
      sensu.sensu_go.bonsai_asset:
        auth: '{{ SENSU_AUTH }}'
        name: sensu/monitoring-plugins
        version: 2.5.2

    - name: Install sensu http plugins
      sensu.sensu_go.bonsai_asset:
        auth: '{{ SENSU_AUTH }}'
        name: sensu-plugins/sensu-plugins-http
        version: 6.0.0

- hosts: sensu_agent

  vars:
    agent_config:
      backend-url: 'ws://archreactor.org:8081'
      subscriptions: '{{ SENSU_CHECKS }}'

  roles:
    - role: sensu.sensu_go.agent
      become: yes
