---

- hosts: all

  vars:
    admin_users:
      - username: josh
        fullname: "Joshua Frank"
        pubkey: "https://github.com/frankjoshua.keys"
      - username: vagrant

  roles:
    - role: ansible-role-admin-users
      become: yes

  tasks:

    - name: Add docker group
      group:
        name: docker
      become: yes

    - name: Add admin users to docker group
      user:
        name: "{{ item.username }}"
        groups: docker
        append: yes
      with_items: "{{ admin_users }}"
      become: yes

    - name: reset ssh connection to reload user groups
      meta: reset_connection